DROP TRIGGER IF EXISTS CHECK_TITLE
go

CREATE TRIGGER CHECK_TITLE ON SAWITZKI_BOOKS
INSTEAD OF INSERT AS
BEGIN
	DECLARE @title VARCHAR(20)
	SELECT @title=title FROM INSERTED
		IF CHARINDEX('Hugo', @title) > 0
			BEGIN
				PRINT ('TITLE CONTAINS HUGO')
			END
		ELSE 
			BEGIN
				INSERT INTO SAWITZKI_BOOKS SELECT * FROM INSERTED
			END

END
go

--INSERT INTO SAWITZKI_BOOKS (isbn, title, pages, price, available) VALUES ('ISBN666', 'Title666', 200, 19.99, 1)
INSERT INTO SAWITZKI_BOOKS (isbn, title, pages, price, available) VALUES ('ISBNHugo666', 'Title667', 200, 19.99, 1)
select * from SAWITZKI_BOOKS 
