--CREATE TABLE SAWITZKI_LOGS (MESSAGE VARCHAR(256), SEVERITY TINYINT, LOG_TIME DATETIME);--
DROP TABLE IF EXISTS SAWITZKI_LOGS 
CREATE TABLE SAWITZKI_LOGS (MESSAGE VARCHAR(256), SEVERITY TINYINT, LOG_TIME DATETIME);--
INSERT INTO SAWITZKI_LOGS (SEVERITY, MESSAGE, LOG_TIME) VALUES (2, 'something happened', '20220922 14:30:01');
INSERT INTO SAWITZKI_LOGS (SEVERITY, MESSAGE, LOG_TIME) VALUES (10, 'something important happened', '20220922 14:30:01');
SELECT * FROM SAWITZKI_LOGS;
--DROP TABLE SAWITZKI_LOGS;