--SELECT SAWITZKI_BOOKS.TITLE, SAWITZKI_AUTHORS.LASTNAME FROM SAWITZKI_BOOKS, SAWITZKI_AUTHORS, SAWITZKI_BOOKS_AUTHORS;
-- Gib mir die Buch-Title des Verlegers 'Springer'

--SELECT ID FROM PUBLISHER WHERE NAME = 'Springer';
--SELECT TITLE FROM BOOKS WHERE PUBLISHER_ID = SELECT ID FROM PUBLISHER WHERE NAME = 'Springer'

SELECT B.TITLE FROM SAWITZKI_PUBLISHERS AS P JOIN SAWITZKI_BOOKS AS B ON B.PUBLISHER_ID = P.ID WHERE NAME='Springer'; 

-- Gib mir die Autoren des Buchs mit der ISBN ISBN2
SELECT A.LASTNAME, A.FIRSTNAME FROM SAWITZKI_BOOKS AS B JOIN SAWITZKI_BOOKS_AUTHORS as BA ON B.ISBN=BA.ISBN JOIN SAWITZKI_AUTHORS AS A ON BA.AUTHOR_ID=A.ID WHERE B.ISBN='ISBN2';