use publishing
--SELECT SAWITZKI_BOOKS.TITLE, SAWITZKI_AUTHORS.LASTNAME FROM SAWITZKI_BOOKS, SAWITZKI_AUTHORS, SAWITZKI_BOOKS_AUTHORS;
-- Gib mir die Buch-Title des Verlegers 'Springer'

--SELECT ID FROM PUBLISHER WHERE NAME = 'Springer';
--SELECT TITLE FROM BOOKS WHERE PUBLISHER_ID = SELECT ID FROM PUBLISHER WHERE NAME = 'Springer'

-- SELECT B.TITLE FROM SAWITZKI_PUBLISHERS AS P JOIN SAWITZKI_BOOKS AS B ON B.PUBLISHER_ID = P.ID WHERE NAME='Springer'; 

-- Gib mir die Autoren des Buchs mit der ISBN ISBN2
-- SELECT A.LASTNAME, A.FIRSTNAME FROM SAWITZKI_BOOKS AS B JOIN SAWITZKI_BOOKS_AUTHORS as BA ON B.ISBN=BA.ISBN JOIN SAWITZKI_AUTHORS AS A ON BA.AUTHOR_ID=A.ID WHERE B.ISBN='ISBN2';

-- SELECT PUB.NAME, AD.CITY, AD.STREET FROM SAWITZKI_PUBLISHERS AS PUB JOIN SAWITZKI_PUBLISHERS_ADDRESSES AS PA ON PUB.ID=PA.PUBLISHER_ID JOIN SAWITZKI_ADDRESSES AS AD ON PA.ADDRESS_ID=AD.ID WHERE PUB.NAME = 'Springer';
-- SELECT AU.LASTNAME, AD.CITY, AD.STREET FROM SAWITZKI_AUTHORS AS AU JOIN SAWITZKI_AUTHORS_ADDRESSES AS AA ON AU.ID=AA.AUTHOR_ID JOIN SAWITZKI_ADDRESSES AS AD ON AA.ADDRESS_ID=AD.ID;
SELECT ISBN, TITLE FROM SAWITZKI_BOOKS UNION SELECT ISBN, TITLE FROM SAWITZKI_SPECIALISTBOOKS ;
SELECT 'Publisher' AS TYPE, NAME AS NAME FROM SAWITZKI_PUBLISHERS UNION SELECT 'Book' AS TYPE, TITLE as NAME from SAWITZKI_BOOKS UNION SELECT 'Author' as TYPE, LASTNAME FROM SAWITZKI_AUTHORS;