use publishing 
DROP TABLE IF EXISTS SAWITZKI_BOOKS_AUTHORS;
DROP TABLE IF EXISTS SAWITZKI_PUBLISHERS_ADDRESSES;
DROP TABLE IF EXISTS SAWITZKI_AUTHORS_ADDRESSES;

DROP TABLE IF EXISTS SAWITZKI_BOOKS;
DROP TABLE IF EXISTS SAWITZKI_SPECIALISTBOOKS;
DROP TABLE IF EXISTS SAWITZKI_PUBLISHERS;
DROP TABLE IF EXISTS SAWITZKI_STORE;
DROP TABLE IF EXISTS SAWITZKI_AUTHORS;
DROP TABLE IF EXISTS SAWITZKI_ADDRESSES;


CREATE TABLE SAWITZKI_PUBLISHERS (
	ID INT IDENTITY(1, 1), 
	NAME VARCHAR(50) NOT NULL, PRIMARY KEY (ID)
	);
CREATE TABLE SAWITZKI_BOOKS (
	ISBN VARCHAR(20) NOT NULL UNIQUE, 
	TITLE VARCHAR(100) UNIQUE NOT NULL, 
	PAGES INT CHECK (PAGES > 0), 
	PRICE FLOAT CHECK (PRICE >= 0), 
	AVAILABLE BIT NOT NULL, 
	PUBLISHER_ID INT NOT NULL, 
	PRIMARY KEY (ISBN), 
	FOREIGN KEY (PUBLISHER_ID) REFERENCES SAWITZKI_PUBLISHERS(ID)
	);
CREATE TABLE SAWITZKI_SPECIALISTBOOKS (
	ISBN VARCHAR(20), 
	TITLE VARCHAR(100) UNIQUE NOT NULL, 
	PAGES INT CHECK (PAGES > 0), 
	PRICE FLOAT CHECK (PRICE >= 0), 
	AVAILABLE BIT NOT NULL,
	TOPIC VARCHAR(20),
	PRIMARY KEY (ISBN) 
);
CREATE TABLE SAWITZKI_AUTHORS(
	ID INT IDENTITY(1, 1), 
	LASTNAME VARCHAR(50) NOT NULL, 
	FIRSTNAME VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID)
	
)
CREATE TABLE SAWITZKI_BOOKS_AUTHORS(
	ISBN VARCHAR(20),
	AUTHOR_ID INT,
	PRIMARY KEY (ISBN, AUTHOR_ID),
	FOREIGN KEY (ISBN) REFERENCES SAWITZKI_BOOKS(ISBN),
	FOREIGN KEY (AUTHOR_ID) REFERENCES SAWITZKI_AUTHORS(ID)
)
CREATE TABLE SAWITZKI_STORE (CATEGORY VARCHAR(20), ITEM VARCHAR(20), STOCK INT CHECK (STOCK >= 0), PRIMARY KEY (CATEGORY, ITEM));

CREATE TABLE SAWITZKI_ADDRESSES (
	ID INT IDENTITY(1, 1),
	CITY VARCHAR(50),
	STREET VARCHAR(50), 
	PRIMARY KEY (ID)
)
CREATE TABLE SAWITZKI_PUBLISHERS_ADDRESSES(
	PUBLISHER_ID INT,
	ADDRESS_ID INT,
	PRIMARY KEY (PUBLISHER_ID, ADDRESS_ID),
	FOREIGN KEY (PUBLISHER_ID) REFERENCES SAWITZKI_PUBLISHERS(ID),
	FOREIGN KEY (ADDRESS_ID) REFERENCES SAWITZKI_ADDRESSES(ID)
)
CREATE TABLE SAWITZKI_AUTHORS_ADDRESSES(
	AUTHOR_ID INT,
	ADDRESS_ID INT,
	PRIMARY KEY (AUTHOR_ID, ADDRESS_ID),
	FOREIGN KEY (AUTHOR_ID) REFERENCES SAWITZKI_AUTHORS(ID),
	FOREIGN KEY (ADDRESS_ID) REFERENCES SAWITZKI_ADDRESSES(ID)
)


INSERT INTO SAWITZKI_PUBLISHERS (NAME) VALUES ('Springer');
INSERT INTO SAWITZKI_BOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID) SELECT 'ISBN1', 'Title1', 200, 19.99, 1, ID FROM SAWITZKI_PUBLISHERS WHERE NAME='Springer';
INSERT INTO SAWITZKI_BOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID) SELECT 'ISBN2', 'Title3', 200, 19.99, 1, ID FROM SAWITZKI_PUBLISHERS WHERE NAME='Springer';
INSERT INTO SAWITZKI_AUTHORS (LASTNAME, FIRSTNAME) VALUES ('Mustermann', 'Hans');
INSERT INTO SAWITZKI_AUTHORS (LASTNAME, FIRSTNAME) VALUES ('Müller', 'Frieda');
INSERT INTO SAWITZKI_AUTHORS (LASTNAME, FIRSTNAME) VALUES ('Pausenkurt', 'Pascal');
INSERT INTO SAWITZKI_BOOKS_AUTHORS (ISBN, AUTHOR_ID) SELECT 'ISBN1', ID FROM SAWITZKI_AUTHORS WHERE LASTNAME = 'Mustermann'
INSERT INTO SAWITZKI_BOOKS_AUTHORS (ISBN, AUTHOR_ID) SELECT 'ISBN2', ID FROM SAWITZKI_AUTHORS WHERE LASTNAME = 'Müller'
INSERT INTO SAWITZKI_BOOKS_AUTHORS (ISBN, AUTHOR_ID) SELECT 'ISBN2', ID FROM SAWITZKI_AUTHORS WHERE LASTNAME = 'Pausenkurt'

INSERT INTO SAWITZKI_ADDRESSES (CITY, STREET) VALUES ('München', 'Marienplatz')
INSERT INTO SAWITZKI_ADDRESSES (CITY, STREET) VALUES ('Berlin', 'Alexanderplatz')
INSERT INTO SAWITZKI_ADDRESSES (CITY, STREET) VALUES ('Stuttgart', 'Schlossplatz')

INSERT INTO SAWITZKI_AUTHORS_ADDRESSES (AUTHOR_ID, ADDRESS_ID) SELECT AU.ID, AD.ID FROM SAWITZKI_AUTHORS AS AU, SAWITZKI_ADDRESSES AS AD  WHERE AU.LASTNAME = 'Pausenkurt' AND AD.CITY= 'Berlin'
INSERT INTO SAWITZKI_AUTHORS_ADDRESSES (AUTHOR_ID, ADDRESS_ID) SELECT AU.ID, AD.ID FROM SAWITZKI_AUTHORS AS AU, SAWITZKI_ADDRESSES AS AD  WHERE AU.LASTNAME = 'Müller' AND AD.CITY= 'München'
INSERT INTO SAWITZKI_AUTHORS_ADDRESSES (AUTHOR_ID, ADDRESS_ID) SELECT AU.ID, AD.ID FROM SAWITZKI_AUTHORS AS AU, SAWITZKI_ADDRESSES AS AD  WHERE AU.LASTNAME = 'Mustermann' AND AD.CITY= 'Stuttgart'

INSERT INTO SAWITZKI_PUBLISHERS_ADDRESSES (PUBLISHER_ID, ADDRESS_ID) SELECT PUB.ID, AD.ID FROM SAWITZKI_PUBLISHERS AS PUB, SAWITZKI_ADDRESSES AS AD  WHERE PUB.NAME = 'Springer' AND AD.CITY= 'Berlin'

INSERT INTO SAWITZKI_SPECIALISTBOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, TOPIC) VALUES('ISBN42', 'Title42', 200, 19.99, 1, 'Science');


DECLARE @publisherCounter INT;
DECLARE @booksCounter INT;
DECLARE @booksNumber INT;
SET @publisherCounter=1;

WHILE (@publisherCounter <=3)
BEGIN
	INSERT INTO SAWITZKI_PUBLISHERS (NAME) VALUES ('Publisher' + CONVERT(VARCHAR, @publisherCounter));
	SET @booksCounter=1;
	WHILE (@booksCounter <=10)
	BEGIN
		SET @booksNumber=@publisherCounter*1000 + @booksCounter;
		print (@booksNumber)
		INSERT INTO SAWITZKI_BOOKS (ISBN, TITLE, PRICE, PAGES, AVAILABLE, PUBLISHER_ID) SELECT 'Isbn' + CONVERT(VARCHAR, @booksNumber), 'Title' + CONVERT(VARCHAR, @booksNumber), 1.99 + @booksCounter, 10*@booksCounter, 1, ID FROM SAWITZKI_PUBLISHERS WHERE NAME = 'Publisher' + CONVERT(VARCHAR, @publisherCounter);
		SET @booksCounter = @booksCounter + 1;
	END
	SET @publisherCounter = @publisherCounter + 1;
END
