DROP TABLE IF EXISTS SAWITZKI_PUBLISHERS;
DROP TABLE IF EXISTS SAWITZKI_BOOKS;
DROP TABLE IF EXISTS SAWITZKI_STORE;

CREATE TABLE SAWITZKI_PUBLISHERS (ID INT IDENTITY(1, 1), NAME VARCHAR(50), PRIMARY KEY (ID));
CREATE TABLE SAWITZKI_BOOKS (ISBN VARCHAR(20), TITLE VARCHAR(100) UNIQUE NOT NULL, PAGES INT, PRICE FLOAT, AVAILABLE BIT NOT NULL, PUBLISHER_ID INT NOT NULL, PRIMARY KEY (ISBN), FOREIGN KEY (PUBLISHER_ID) REFERENCES SAWITZKI_PUBLISHERS(ID));
CREATE TABLE SAWITZKI_STORE (CATEGORY VARCHAR(20), ITEM VARCHAR(20), STOCK INT, PRIMARY KEY (CATEGORY, ITEM));
