DROP TABLE IF EXISTS SAWITZKI_BOOKS_AUTHORS;
DROP TABLE IF EXISTS SAWITZKI_BOOKS;
DROP TABLE IF EXISTS SAWITZKI_PUBLISHERS;
DROP TABLE IF EXISTS SAWITZKI_STORE;
DROP TABLE IF EXISTS SAWITZKI_AUTHORS;

CREATE TABLE SAWITZKI_PUBLISHERS (
	ID INT IDENTITY(1, 1), 
	NAME VARCHAR(50) NOT NULL, PRIMARY KEY (ID)
	);
CREATE TABLE SAWITZKI_BOOKS (
	ISBN VARCHAR(20) NOT NULL UNIQUE, 
	TITLE VARCHAR(100) UNIQUE NOT NULL, 
	PAGES INT CHECK (PAGES > 0), 
	PRICE FLOAT CHECK (PRICE >= 0), 
	AVAILABLE BIT NOT NULL, 
	PUBLISHER_ID INT NOT NULL, 
	PRIMARY KEY (ISBN), 
	FOREIGN KEY (PUBLISHER_ID) REFERENCES SAWITZKI_PUBLISHERS(ID)
	);

CREATE TABLE SAWITZKI_AUTHORS(
	ID INT IDENTITY(1, 1), 
	LASTNAME VARCHAR(50) NOT NULL, 
	FIRSTNAME VARCHAR(50) NOT NULL, 
	PRIMARY KEY (ID)
	
)
CREATE TABLE SAWITZKI_BOOKS_AUTHORS(
	ISBN VARCHAR(20),
	AUTHOR_ID INT,
	PRIMARY KEY (ISBN, AUTHOR_ID),
	FOREIGN KEY (ISBN) REFERENCES SAWITZKI_BOOKS(ISBN),
	FOREIGN KEY (AUTHOR_ID) REFERENCES SAWITZKI_AUTHORS(ID)
)
CREATE TABLE SAWITZKI_STORE (CATEGORY VARCHAR(20), ITEM VARCHAR(20), STOCK INT CHECK (STOCK >= 0), PRIMARY KEY (CATEGORY, ITEM));
