INSERT INTO SAWITZKI_PUBLISHERS (NAME) VALUES ('Springer');
INSERT INTO SAWITZKI_BOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID) VALUES ('ISBN1', 'Title1', 200, 19.99, 1, 1);
INSERT INTO SAWITZKI_BOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID) VALUES ('ISBN2', 'Title2', 100, 29.99, 1, 1);
INSERT INTO SAWITZKI_AUTHORS (LASTNAME, FIRSTNAME) VALUES ('Mustermann', 'Hans');
INSERT INTO SAWITZKI_AUTHORS (LASTNAME, FIRSTNAME) VALUES ('M�ller', 'Frieda');
INSERT INTO SAWITZKI_AUTHORS (LASTNAME, FIRSTNAME) VALUES ('Pausenkurt', 'Pascal');
INSERT INTO SAWITZKI_BOOKS_AUTHORS (ISBN, AUTHOR_ID) VALUES ('ISBN1', 1)
INSERT INTO SAWITZKI_BOOKS_AUTHORS (ISBN, AUTHOR_ID) VALUES ('ISBN2', 2)
INSERT INTO SAWITZKI_BOOKS_AUTHORS (ISBN, AUTHOR_ID) VALUES ('ISBN2', 3)
