INSERT INTO SAWITZKI_PUBLISHERS (NAME) VALUES ('Addison-Wesley');
INSERT INTO SAWITZKI_BOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID) SELECT 'ISBN4', 'Title4', 200, 19.99, 1, ID FROM SAWITZKI_PUBLISHERS WHERE NAME='Addison-Wesley';
