use publishing 
DROP PROCEDURE IF EXISTS SAWITZKI_CREATE_BOOK
DROP PROCEDURE IF EXISTS SAWITZKI_DELETE_BOOK
GO
CREATE PROCEDURE SAWITZKI_CREATE_BOOK @isbn VARCHAR(20), @title VARCHAR(50), @publisherName VARCHAR(50) as

BEGIN
	INSERT INTO SAWITZKI_BOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID) select @isbn, @title, 200, 19.99, 1, ID FROM SAWITZKI_PUBLISHERS WHERE NAME=@publisherName;
END

GO

CREATE PROCEDURE SAWITZKI_DELETE_BOOK @isbn VARCHAR(20) as

BEGIN
	DELETE FROM SAWITZKI_BOOKS_AUTHORS  WHERE ISBN=@isbn
	DELETE FROM SAWITZKI_BOOKS  WHERE ISBN=@isbn

END