use publishing 
DROP VIEW IF EXISTS SCHOOL_BOOKS
DROP VIEW IF EXISTS SPECIALIST_BOOKS
DROP VIEW IF EXISTS ALL_BOOKS
GO
CREATE VIEW SCHOOL_BOOKS AS 
	SELECT * FROM BOOKS WHERE DISCRIMINATOR = 'school'
GO
CREATE VIEW SPECIALIST_BOOKS AS 
	SELECT * FROM BOOKS WHERE DISCRIMINATOR = 'specialist'
GO
CREATE VIEW ALL_BOOKS AS 
	SELECT ISBN, TITLE FROM BOOKS UNION SELECT ISBN, TITLE FROM SPECIALISTBOOKS 
GO

