use publishing 
DROP VIEW IF EXISTS SAWITZKI_SCHOOL_BOOKS
DROP VIEW IF EXISTS SAWITZKI_SPECIALIST_BOOKS
DROP VIEW IF EXISTS SAWITZKI_ALL_BOOKS
GO
CREATE VIEW SAWITZKI_SCHOOL_BOOKS AS 
	SELECT * FROM SAWITZKI_BOOKS WHERE DISCRIMINATOR = 'school'
GO
CREATE VIEW SAWITZKI_SPECIALIST_BOOKS AS 
	SELECT * FROM SAWITZKI_BOOKS WHERE DISCRIMINATOR = 'specialist'
GO
CREATE VIEW SAWITZKI_ALL_BOOKS AS 
	SELECT ISBN, TITLE FROM SAWITZKI_BOOKS UNION SELECT ISBN, TITLE FROM SAWITZKI_SPECIALISTBOOKS 
GO

