DROP TABLE IF EXISTS ISSUES;
CREATE TABLE ISSUES (
	ID int IDENTITY(1,1) PRIMARY KEY,
	ASSIGNEE int,
	DESCRIPTION VARCHAR(500) NOT NULL,
	STATUS VARCHAR(50) NOT NULL,
	CONSTRAINT STATUS_CHECK
	CHECK (STATUS IN ('OPEN', 'IN PROGRESS', 'FINISHED')),
	PRIORITY VARCHAR(50) NOT NULL,
	CONSTRAINT PRIO_CHECK
	CHECK (PRIORITY IN ('LOW','MEDIUM', 'HIGH', 'CRITICAL'))
	);
	
