INSERT INTO USERS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('Tom', 'Thomas', 'J');
INSERT INTO USERS (USERNAME, FIRSTNAME, LASTNAME) VALUES ('J', 'Jerry', 'Mouse');

INSERT INTO ISSUES (DESCRIPTION, STATUS, PRIORITY) VALUES ('Ich bin der erste Issue', 'OPEN', 'LOW');
INSERT INTO ISSUES (DESCRIPTION, STATUS, PRIORITY) VALUES ('Ich bin der zweite Issue', 'OPEN', 'MEDIUM');
INSERT INTO ISSUES (DESCRIPTION, STATUS, PRIORITY) VALUES ('Ich bin der dritte Issue', 'OPEN', 'HIGH');
INSERT INTO ISSUES (DESCRIPTION, STATUS, PRIORITY) VALUES ('Ich bin der erste Error Issue', 'IN PROGRESS', 'LOW');
INSERT INTO ISSUES (DESCRIPTION, STATUS, PRIORITY) VALUES ('Ich bin der ERROR', 'ERROR', 'ERROR');

UPDATE ISSUES SET STATUS = 'IN PROGRESS', ASSIGNEE = 1 WHERE ID = 1;
UPDATE ISSUES SET STATUS = 'IN PROGRESS', ASSIGNEE = 2 WHERE ID = 2;
UPDATE ISSUES SET STATUS = 'CLOSED' WHERE ID = 1;
UPDATE ISSUES SET STATUS = 'FINISHED', ASSIGNEE = NULL WHERE ID = 1;